name: Markdown Linter

on:
    push:
        branches: [$default-branch]
    pull_request:
        branches: [$default-branch]

jobs:
  mdlinter:
    name: Lint markdown file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint Markdown files
      uses: avto-dev/markdown-lint@v1
      with:
        rules: '/lint/rules/changelog.js'
        config: '/lint/config/changelog.yml'
        args: './CHANGELOG.md'
